# Generated by Django 4.0.4 on 2022-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('date_of_birth', models.DateField(blank=True)),
                ('formation', models.CharField(help_text='Образование', max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image_profile/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
